spring.application.name=space-cats

application.feature.spaceCats.enabled=true
application.feature.kittyProducts.enabled=true


spring.datasource.url=jdbc:postgresql://localhost:5432/space_cats_marketplace
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:liquibase/changelog.yaml
spring.liquibase.enabled=true